try {
    console.log(a);
    let a = 3
} catch (err) {
    console.log("Let must be declared before use");
}

